name: Azure Web App Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install root dependencies
        run: npm install

      - name: Build React frontend
        run: npm run build

      - name: Install backend dependencies
        run: |
          cd backend
          npm install --production

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

      - name: Health check
        run: |
          curl -sSf https://${{ secrets.AZURE_WEBAPP_NAME }}.azurewebsites.net/api/health || exit 1