name: CI - Build and Test

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: 'Test and Build'
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install frontend dependencies
      run: npm ci
    
    - name: Install backend dependencies
      run: |
        cd backend
        npm install
    
    - name: Run frontend tests
      run: npm test -- --coverage --watchAll=false
      env:
        CI: true
    
    - name: Build frontend
      run: npm run build
    
    - name: Test backend server
      run: |
        cd backend
        node -e "console.log('Backend syntax check passed')"
    
    - name: Upload coverage reports
      if: matrix.node-version == '18.x'
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage/lcov.info
        flags: frontend
        name: frontend-coverage